namespace ButterBror.Application;

public class Localization
{
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> DefaultTranslations => 
        new Dictionary<string, IReadOnlyDictionary<string, string>>()
    {
        { 
            "RU_RU",
            new Dictionary<string, string>()
            {
                // Ban phrases
                { "command.banphrases.usage", "Использование: banphrases <set|get|list|test|delete> <global|channel> [категория] [шаблон|hastebin]" },
                { "command.banphrases.unknown", "Неизвестное действие. Используйте: set, get, list, test, delete" },
                { "command.banphrases.set.usage", "Использование: banphrases set <global|channel> <категория> <шаблон|hastebin>" },
                { "command.banphrases.set.fail", "Не удалось получить шаблон из Hastebin. Для получения дополнительной информации см. консоль" },
                { "command.banphrases.set.regex_fail", "Не удалось установить категорию блокфразы. Проверьте синтаксис шаблона регулярного выражения. Для получения дополнительной информации см. консоль" },
                { "command.banphrases.set.success", "Установлено {0} {1} фраз из регулярного выражения в категории '{2}'" },
                { "command.banphrases.get.usage", "Использование: banphrases get <global|channel> <категория>" },
                { "command.banphrases.get.category_not_found", "Категория '{0}' не найдена в разделе '{1}'" },
                { "command.banphrases.get.success", "Запрещенные фразы в разделе '{0}' категории '{1}': {2}" },
                { "command.banphrases.get.fail", "Не удалось загрузить шаблон на Hastebin. Для получения дополнительной информации см. консоль" },
                { "command.banphrases.list.not_found", "Категории в разделе '{0}' не найдены" },
                { "command.banphrases.list.title", "Список категорий в разделе '{0}':" },
                { "command.banphrases.list.success", "Все категории в разделе '{0}': {1}" },
                { "command.banphrases.list.fail", "Не удалось загрузить шаблон на Hastebin. Для получения дополнительной информации см. консоль" },
                { "command.banphrases.test.usage", "Использование: banphrases test <global|channel> <сообщение>" },
                { "command.banphrases.test.success", "Сообщение прошло фильтр" },
                { "command.banphrases.test.fail", "Сообщение не прошло фильтр. Раздел: '{0}', категория: '{1}'" },
                { "command.banphrases.test.matched", ", соответствует: '{0}'" },
                { "command.banphrases.test.regex", ", regex: '{0}'"},
                { "command.banphrases.delete.usage", "Использование: banphrases delete <global|channel> <категория>" },
                { "command.banphrases.delete.success", "Удалена категория блок-фраз '{0}' из раздела '{1}'" },
                { "command.banphrases.delete.fail", "Не удалось удалить категорию '{0}'. Для получения дополнительной информации см. консоль" },
                // Locale
                { "command.locale.set.success", "Ваш язык установлен на русский" },
                { "command.locale.admin.set.permission", "Доступ запрещен" },
                { "command.locale.admin.set.usage", "Использование: locale set <локаль> <hastebin_url>" },
                { "command.locale.admin.set.invalid", "Неверный формат перевода: отсутствует объект 'strings'" },
                { "command.locale.admin.set.success", "Локаль {0} успешно обновлена" },
                { "command.locale.delete.permission", "Доступ запрещен" },
                { "command.locale.delete.usage", "Использование: locale delete <локаль>" },
                { "command.locale.delete.unknown", "Неизвестная локаль: {0}" },
                { "command.locale.delete.default", "Невозможно удалить локаль по умолчанию" },
                { "command.locale.delete.success", "Локаль {0} удалена" },
                { "command.locale.delete.fail", "Не удалось удалить локаль {0}" },
                { "command.locale.view.permission", "Доступ запрещен" },
                { "command.locale.view.usage", "Использование: locale view <locale>" },
                { "command.locale.view.unknown", "Неизвестная локаль: {0}" },
                { "command.locale.view.not_found", "Файл перевода не найден: {0}" },
                { "command.locale.view.success", "Локаль {0} загружена: {1}" },
                { "command.locale.reload.permission", "Доступ запрещен" },
                { "command.locale.reload.success", "Кэш локализации успешно перезагружен." },
                // Reload module
                { "command.module_reload.usage", "Использование: reloadmodule <chat|command> <id-модуля>" },
                { "command.module_reload.unknown", "Неизвестный тип модуля. Используйте 'chat' или 'command'" },
                { "command.module_reload.not_found", "Модуль не найден" },
                { "command.module_reload.not_found_local", "Модуль не был найден в файлах" },
                { "command.module_reload.exception", "Произошла ошибка. Подробности смотрите в консоли" },
                { "command.module_reload.success", "Модуль успешно перезагружен" },
                // User info
                { "command.user_info.not_found", "Пользователь не найден. Попробуйте использовать его полный никнейм или ID" },
                { "command.user_info.success", "Имя пользователя: {0}, Идентификатор: {1}" },
                // Core
                { "core.error.report", "Произошла ошибка! (ID: {0})" },
                { "core.bot.banphrase", "Сообщение не прошло модерацию чата" },
                { "core.bot.command.not_found", "Команда '{0}' не найдена" },
                { "core.bot.command.compatibility", "Команда '{0}' несовместима с платформой '{1}'" },
                { "core.bot.command.permission", "Доступ запрещен" },
                { "core.bot.command.cooldown", "Команда '{0}' находится в режиме ожидания. Пожалуйста, подождите {1} секунд" },
                // Word
                { "word.second", "с." },
                { "word.minute", "м." },
                { "word.hour", "ч." },
                { "word.day", "д." },
                { "word.month", "мес." },
                { "word.year", "г." },
            }
        },
        {
            "EN_US",
            new Dictionary<string, string>()
            {
                // Ban phrases
                { "command.banphrases.usage", "Usage: banphrases <set|get|list|test|delete> <global|channel> [category] [pattern|hastebin]" },
                { "command.banphrases.unknown", "Unknown action. Use: set, get, list, test, delete" },
                { "command.banphrases.set.usage", "Usage: banphrases set <global|channel> <category> <pattern|hastebin-url>" },
                { "command.banphrases.set.fail", "Failed to fetch pattern from Hastebin. For more information, see the console" },
                { "command.banphrases.set.regex_fail", "Failed to set banphrase category. Check regex pattern syntax. For more information, see the console" },
                { "command.banphrases.set.success", "Setted {0} {1} banphrases from your regex in category '{2}'" },
                { "command.banphrases.get.usage", "Usage: banphrases get <global|channel> <category>" },
                { "command.banphrases.get.category_not_found", "Category '{0}' not found in section '{1}'" },
                { "command.banphrases.get.success", "Banned phrases in the '{0}' section of the '{1}' category: {2}" },
                { "command.banphrases.get.fail", "Failed to upload pattern to Hastebin. For more information, see the console" },
                { "command.banphrases.list.not_found", "No categories found in section '{0}'" },
                { "command.banphrases.list.title", "List of categories in the '{0}' section:" },
                { "command.banphrases.list.success", "Categories in the '{0}' section: {1}" },
                { "command.banphrases.list.fail", "Failed to upload pattern to Hastebin. For more information, see the console" },
                { "command.banphrases.test.usage", "Usage: banphrases test <global|channel> <message>" },
                { "command.banphrases.test.success", "The message passed the filter" },
                { "command.banphrases.test.fail", "The message didn't pass the filter. Section: '{0}', category: '{1}'" },
                { "command.banphrases.test.matched", ", matched: '{0}'" },
                { "command.banphrases.test.regex", ", regex: '{0}'"},
                { "command.banphrases.delete.usage", "Usage: banphrases delete <global|channel> <category>" },
                { "command.banphrases.delete.success", "Deleted banphrase category '{0}' from section '{1}'" },
                { "command.banphrases.delete.fail", "Failed to delete category '{0}'" },
                // Locale
                { "command.locale.usage", "This command is always in English by default. Usage: locale set <locale> [url] | list | delete <locale> | view <locale> | reload" },
                { "command.locale.unknown", "Unknown action. Use: set, list, delete, view, reload" },
                { "command.locale.set.usage", "Usage: locale set <locale> [url]" },
                { "command.locale.set.invalid", "Unknown locale '{0}'. Use 'locale list' to see available options" },
                { "command.locale.set.user_not_found", "User profile not found" },
                { "command.locale.set.success", "Your language has been set to english" },
                { "command.locale.list", "Available Locales (default: {0})" },
                { "command.locale.admin.set.permission", "Permission denied" },
                { "command.locale.admin.set.usage", "Usage: locale set <locale> <hastebin_url>" },
                { "command.locale.admin.set.invalid", "Invalid translation format: missing 'strings' object" },
                { "command.locale.admin.set.success", "Locale {0} updated successfully" },
                { "command.locale.delete.permission", "Permission denied" },
                { "command.locale.delete.usage", "Usage: locale delete <locale>" },
                { "command.locale.delete.unknown", "Unknown locale: {0}" },
                { "command.locale.delete.default", "Cannot delete the default locale" },
                { "command.locale.delete.success", "Locale {0} deleted" },
                { "command.locale.delete.fail", "Failed to delete locale {0}" },
                { "command.locale.view.permission", "Permission denied" },
                { "command.locale.view.usage", "Usage: locale view <locale>" },
                { "command.locale.view.unknown", "Unknown locale: {0}" },
                { "command.locale.view.not_found", "Translation file not found: {0}" },
                { "command.locale.view.success", "Locale {0} uploaded: {1}" },
                { "command.locale.reload.permission", "Permission denied" },
                { "command.locale.reload.success", "Localization cache reloaded successfully" },
                // Reload module
                { "command.module_reload.usage", "Usage: reloadmodule <chat|command> <moduleId>" },
                { "command.module_reload.unknown", "Unknown module type. Use 'chat' or 'command'" },
                { "command.module_reload.not_found", "Module not found" },
                { "command.module_reload.not_found_local", "The module was not found in the files" },
                { "command.module_reload.exception", "An error occurred. See the console for details" },
                { "command.module_reload.success", "Module reloaded successfully" },
                // User info
                { "command.user_info.not_found", "User not found. Try using their full nickname or ID" },
                { "command.user_info.success", "Username: {0}, Id: {1}" },
                // Core
                { "core.error.report", "An error occurred! (Id: {0})" },
                { "core.bot.connected", "Bot connected successfully :P" },
                { "core.bot.banphrase", "The message did not pass chat moderation" },
                { "core.bot.command.not_found", "Command '{0}' not found" },
                { "core.bot.command.compatibility", "Command '{0}' is not compatible with platform '{1}'" },
                { "core.bot.command.permission", "Permission denied" },
                { "core.bot.command.cooldown", "Command '{0}' is on cooldown. Please, wait {1} seconds" },
                // Word
                { "word.second", "s." },
                { "word.minute", "m." },
                { "word.hour", "h." },
                { "word.day", "d." },
                { "word.month", "mo." },
                { "word.year", "y." },
            }
        }
    };
}